import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../data/models/course.dart';
import '../../data/providers.dart';
import '../../data/settings/app_settings.dart';
import '../../data/settings/settings_controller.dart';
import '../../l10n/generated/app_localizations.dart';
import '../pages/course_detail_page.dart';
import '../settings/timetable_settings_page.dart';

/// Ticks once a minute so the "current period" highlight doesn't go stale
/// while the page stays open (e.g. still showing period 5 late at night).
final _clockProvider = StreamProvider<DateTime>(
    (ref) => Stream.periodic(const Duration(minutes: 1), (_) => DateTime.now()));

/// Weekly timetable generated by parsing KLMS course names.
class TimetablePage extends ConsumerWidget {
  const TimetablePage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final l10n = AppLocalizations.of(context);
    final settings = ref.watch(settingsProvider);
    final courses = ref.watch(coursesProvider).value ?? const <Course>[];

    final days = [
      for (var d = settings.timetableFirstDay;
          d <= settings.timetableLastDay;
          d++)
        d
    ];
    final periods = settings.periodsPerDay;

    // (weekday, period) -> courses in that cell.
    final grid = <(int, int), List<Course>>{};
    for (final course in courses) {
      if (course.hidden) continue;
      for (final slot in course.parsed.slots) {
        if (slot.weekday < settings.timetableFirstDay ||
            slot.weekday > settings.timetableLastDay ||
            slot.period < 1 ||
            slot.period > periods) {
          continue;
        }
        grid.putIfAbsent((slot.weekday, slot.period), () => []).add(course);
      }
    }

    final now = ref.watch(_clockProvider).value ?? DateTime.now();
    final nowMinutes = now.hour * 60 + now.minute;
    final currentDay = now.weekday;
    int? currentPeriod;
    for (var p = 0; p < settings.periodTimes.length && p < periods; p++) {
      final t = settings.periodTimes[p];
      if (nowMinutes >= t.startMinutes && nowMinutes <= t.endMinutes) {
        currentPeriod = p + 1;
        break;
      }
    }

    final locale = Localizations.localeOf(context).toString();
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      appBar: AppBar(
        title: Text(l10n.tabTimetable),
        actions: [
          IconButton(
            tooltip: l10n.timetableSettings,
            icon: const Icon(Icons.tune),
            onPressed: () => Navigator.of(context).push(MaterialPageRoute(
                builder: (_) => const TimetableSettingsPage())),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.fromLTRB(4, 4, 8, 8),
        child: Column(
          children: [
            Row(
              children: [
                const SizedBox(width: 44),
                for (final d in days)
                  Expanded(
                    child: Center(
                      child: Text(
                        _weekdayLabel(d, locale),
                        style: TextStyle(
                          fontWeight: d == currentDay
                              ? FontWeight.bold
                              : FontWeight.normal,
                          color: d == currentDay ? scheme.primary : null,
                        ),
                      ),
                    ),
                  ),
              ],
            ),
            const SizedBox(height: 4),
            Expanded(
              child: Column(
                children: [
                  for (var p = 1; p <= periods; p++)
                    Expanded(
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.stretch,
                        children: [
                          _PeriodGutter(
                            period: p,
                            time: p <= settings.periodTimes.length
                                ? settings.periodTimes[p - 1]
                                : null,
                            highlighted: p == currentPeriod,
                          ),
                          for (final d in days)
                            Expanded(
                              child: _TimetableCell(
                                  courses: grid[(d, p)] ?? const []),
                            ),
                        ],
                      ),
                    ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  static String _weekdayLabel(int weekday, String locale) {
    // 2024-01-01 is a Monday.
    final date = DateTime(2024, 1, weekday);
    return DateFormat.E(locale).format(date);
  }
}

class _PeriodGutter extends StatelessWidget {
  const _PeriodGutter({required this.period, this.time, this.highlighted = false});

  final int period;
  final PeriodTime? time;
  final bool highlighted;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final color = highlighted ? scheme.primary : scheme.outline;
    return SizedBox(
      width: 44,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          if (time != null)
            Text(time!.startLabel,
                style: TextStyle(fontSize: 9, color: color)),
          Text(
            '$period',
            style: TextStyle(
              fontWeight: highlighted ? FontWeight.bold : FontWeight.w500,
              color: highlighted ? scheme.primary : null,
            ),
          ),
          if (time != null)
            Text(time!.endLabel, style: TextStyle(fontSize: 9, color: color)),
        ],
      ),
    );
  }
}

class _TimetableCell extends StatelessWidget {
  const _TimetableCell({required this.courses});

  final List<Course> courses;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    Widget content;
    if (courses.isEmpty) {
      content = Container(
        margin: const EdgeInsets.symmetric(horizontal: 1.5),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(8),
          color: scheme.surfaceContainerLow,
        ),
      );
    } else if (courses.length == 1) {
      content = _CourseChip(course: courses.first);
    } else {
      // Two (or more) courses share a cell: split top/bottom; with three or
      // more the bottom half collapses to "…". The gap between the two
      // stacked chips (margin 1 each) is intentionally smaller than the gap
      // between periods (margin 2.5 on the cell as a whole, below).
      content = Column(
        children: [
          Expanded(child: _CourseChip(course: courses.first, compact: true)),
          Expanded(
            child: courses.length == 2
                ? _CourseChip(course: courses[1], compact: true)
                : Container(
                    margin: const EdgeInsets.symmetric(horizontal: 1.5, vertical: 1),
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(8),
                      color: scheme.secondaryContainer,
                    ),
                    child: Text('…',
                        style: TextStyle(
                            color: scheme.onSecondaryContainer,
                            fontWeight: FontWeight.bold)),
                  ),
          ),
        ],
      );
    }
    return Container(
      margin: const EdgeInsets.symmetric(vertical: 2.5),
      child: content,
    );
  }
}

class _CourseChip extends StatelessWidget {
  const _CourseChip({required this.course, this.compact = false});

  final Course course;
  final bool compact;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final parsed = course.parsed;
    return Container(
      width: double.infinity,
      margin: EdgeInsets.symmetric(horizontal: 1.5, vertical: compact ? 1 : 0),
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8),
        color: scheme.primaryContainer,
      ),
      clipBehavior: Clip.antiAlias,
      child: InkWell(
        onTap: () => Navigator.of(context).push(MaterialPageRoute(
            builder: (_) => CourseDetailPage(course: course))),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 2),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Flexible(
                child: Text(
                  // Timetable always shows the real course title (nicknames
                  // are for task lists only).
                  parsed.displayName,
                  maxLines: compact ? 1 : 3,
                  overflow: TextOverflow.ellipsis,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: compact ? 9.5 : 11,
                    fontWeight: FontWeight.w600,
                    color: scheme.onPrimaryContainer,
                    height: 1.15,
                  ),
                ),
              ),
              if (parsed.room != null)
                Text(
                  parsed.room!,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: TextStyle(
                      fontSize: compact ? 7.5 : 8.5,
                      color: scheme.onPrimaryContainer.withValues(alpha: 0.7)),
                ),
            ],
          ),
        ),
      ),
    );
  }
}
